Repository jenkinsci/incrementals-tools, pull requests merged in 2023-02, with the labels that each got.

#35 Restore trailing slash after `a` or `b`
  git-changelist-maven-extension/src/main/java/io/jenkins/tools/incrementals/git_changelist_maven_extension/Main.java
  git-changelist-maven-extension/src/test/java/io/jenkins/tools/incrementals/git_changelist_maven_extension/MainTest.java
Labels: bug

#37 Refresh component for January 2023
  enforcer-rules/pom.xml
  enforcer-rules/src/main/java/io/jenkins/tools/incrementals/enforcer/RequireExtensionVersion.java
  git-changelist-maven-extension/pom.xml
  lib/pom.xml
  lib/src/main/java/io/jenkins/tools/incrementals/lib/UpdateChecker.java
  maven-plugin/pom.xml
  maven-plugin/src/main/java/io/jenkins/tools/incrementals/maven/IncrementalifyMojo.java
  maven-plugin/src/main/java/io/jenkins/tools/incrementals/maven/UpdateMojo.java
  maven-plugin/src/main/java/io/jenkins/tools/incrementals/maven/util/PluginRef.java
  maven-plugin/src/main/java/io/jenkins/tools/incrementals/maven/util/PluginRefList.java
  pom.xml
Labels: dependencies

#38 Enable Dependabot
  .github/dependabot.yml
Labels: chore
